import { useEffect, useMemo, useState } from "react";
import { FaArrowLeft, FaCheckCircle, FaHandsHelping, FaUserCheck } from "react-icons/fa";
import { toast } from "react-toastify";
import API from "../../services/api";
import "./GovernmentRequests.css";

const statusClass = (status = "") => status.toLowerCase().replace(/\s+/g, "-");

function GovernmentAssistance({ onBack }) {
  const [items, setItems] = useState([]), [ngos, setNgos] = useState([]), [volunteers, setVolunteers] = useState([]);
  const [loading, setLoading] = useState(true), [busyId, setBusyId] = useState(""), [search, setSearch] = useState("");
  const [priority, setPriority] = useState("All"), [status, setStatus] = useState("All"), [selected, setSelected] = useState(null);
  const [assignType, setAssignType] = useState(""), [assignValue, setAssignValue] = useState("");

  const loadData = async () => { try { setLoading(true); const [a, n, v] = await Promise.all([API.get("/government/assistance"), API.get("/government/ngos"), API.get("/government/volunteers")]); setItems(a.data.assistance || []); setNgos(n.data.ngos || []); setVolunteers(v.data.volunteers || []); } catch (e) { toast.error(e.response?.data?.message || "Failed to load assistance data."); } finally { setLoading(false); } };
  useEffect(() => { loadData(); }, []);
  const filtered = useMemo(() => items.filter((item) => { const q = search.toLowerCase().trim(); const text = [item.assistanceType,item.location,item.description,item.user?.fullName,item.user?.phone].join(" ").toLowerCase(); return (!q || text.includes(q)) && (priority === "All" || item.priority === priority) && (status === "All" || item.status === status); }), [items,search,priority,status]);
  const takeAction = async (id) => { try { setBusyId(id); await API.put(`/government/assistance/${id}/take-action`); toast.success("Government assistance response started."); await loadData(); } catch(e) { toast.error(e.response?.data?.message || "Unable to start response."); } finally { setBusyId(""); } };
  const assign = async () => { if (!selected || !assignType || !assignValue) return toast.warning("Select an assignment first."); try { setBusyId(selected._id); const url = assignType === "NGO" ? `/government/assistance/${selected._id}/assign-ngo` : `/government/assistance/${selected._id}/assign-volunteer`; await API.put(url, assignType === "NGO" ? { ngoId: assignValue } : { volunteerId: assignValue }); toast.success(`${assignType} assigned successfully.`); setSelected(null); setAssignType(""); setAssignValue(""); await loadData(); } catch(e) { toast.error(e.response?.data?.message || "Unable to assign resource."); } finally { setBusyId(""); } };

  return <div className="gov-page">
    <div className="gov-page-header"><button className="gov-back-btn" onClick={onBack}><FaArrowLeft /> Dashboard</button><div><h1>Assistance Monitoring</h1><p>Monitor food, water, medical, shelter and essential-supply requests.</p></div><button className="gov-refresh-btn" onClick={loadData}>Refresh</button></div>
    <div className="gov-info-strip"><FaHandsHelping /> Government coordinates assistance while NGOs and volunteers can continue handling normal requests.</div>
    <div className="gov-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search person, location, assistance type..."/><select value={priority} onChange={e=>setPriority(e.target.value)}><option>All</option><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Pending</option><option>Acknowledged</option><option>In Progress</option><option>Fulfilled</option><option>Rejected</option></select><span className="gov-result-count">{filtered.length} of {items.length} requests</span></div>
    {loading ? <div className="gov-empty">Loading assistance requests...</div> : filtered.length === 0 ? <div className="gov-empty">No assistance requests match the selected filters.</div> : <div className="gov-table-card"><div className="table-responsive"><table className="gov-table"><thead><tr><th>Priority</th><th>Citizen</th><th>Need</th><th>Location</th><th>Assigned</th><th>Status</th><th>Reported</th><th>Action</th></tr></thead><tbody>{filtered.map(item=><tr key={item._id}><td><span className={`gov-pill severity-${statusClass(item.priority)}`}>{item.priority}</span></td><td><strong>{item.user?.fullName || "Unknown"}</strong><small>{item.user?.phone || ""}</small></td><td>{item.assistanceType}</td><td>{item.location || "Location not provided"}</td><td>{item.handledByNGO?.fullName ? `NGO: ${item.handledByNGO.fullName}` : item.assignedVolunteer?.fullName ? `Volunteer: ${item.assignedVolunteer.fullName}` : item.handledByGovernment?.fullName ? `Government: ${item.handledByGovernment.fullName}` : "Unassigned"}</td><td><span className={`gov-pill status-${statusClass(item.status)}`}>{item.status}</span></td><td>{item.createdAt ? new Date(item.createdAt).toLocaleString() : "—"}</td><td><div className="gov-actions"><button className="btn-outline" onClick={()=>setSelected(item)}>Details</button>{!["Fulfilled","Rejected"].includes(item.status) && <button className="btn-primary" disabled={busyId===item._id} onClick={()=>takeAction(item._id)}>{busyId===item._id?"Working...":"Take Action"}</button>}</div></td></tr>)}</tbody></table></div></div>}
    {selected && <div className="gov-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="gov-modal"><div className="gov-modal-head"><div><span className={`gov-pill severity-${statusClass(selected.priority)}`}>{selected.priority}</span><h2>{selected.assistanceType}</h2></div><button onClick={()=>setSelected(null)}>×</button></div><div className="gov-detail-grid"><div><b>Citizen</b><span>{selected.user?.fullName||"Unknown"}</span></div><div><b>Contact</b><span>{selected.user?.phone||"—"}</span></div><div><b>Location</b><span>{selected.location||"—"}</span></div><div><b>Status</b><span>{selected.status}</span></div><div className="wide"><b>Description</b><span>{selected.description||"No description provided."}</span></div></div><div className="gov-assign-box"><h3><FaUserCheck/> Coordinate Assistance</h3><div className="assign-row"><select value={assignType} onChange={e=>{setAssignType(e.target.value);setAssignValue("")}}><option value="">Choose type</option><option value="NGO">NGO</option><option value="Volunteer">Volunteer</option></select><select value={assignValue} disabled={!assignType} onChange={e=>setAssignValue(e.target.value)}><option value="">Choose {assignType||"resource"}</option>{assignType==="NGO"?ngos.map(n=><option key={n._id} value={n._id}>{n.fullName} — {n.activeRequests||0} active</option>):volunteers.map(v=><option key={v._id} value={v._id}>{v.fullName} — {v.available?"Available":`${v.activeAssignments} active`}</option>)}</select><button className="btn-primary" onClick={assign} disabled={!assignType||!assignValue||busyId===selected._id}>Assign</button></div></div>{!["Fulfilled","Rejected"].includes(selected.status)&&<button className="btn-government-action" onClick={()=>{takeAction(selected._id);setSelected(null)}}><FaCheckCircle/> Government takes responsibility</button>}</div></div>}
  </div>;
}
export default GovernmentAssistance;
